export type { IPersistenceAdapter, ProjectSummary } from './types'
export { LocalAdapter, localAdapter } from './local'
export { CmsAdapter, cmsAdapter } from './cms'
export { getCmsPublishStatus, publishCmsDraft } from './cmsPublish'
export type { CmsPublishResult, CmsPublishStatus } from './cmsPublish'
export { listCmsMediaAssets, uploadCmsMediaAsset } from './cmsMedia'
export type { CmsMediaAsset } from './cmsMedia'
export { getCmsSetupStatus, loginCms, logoutCms, probeCmsSession, setupCms } from './cmsAuth'
export type { CmsLoginInput, CmsSetupInput, CmsSetupStatus } from './cmsAuth'
export { validateProject, ValidationError } from './validate'
// usePersistence moved to src/editor/hooks/usePersistence.ts (Constraint #179 — no React in core)
